name: hangul_utils
description: hangul_utils is an effective package for handling Hangul in Dart.
version: 1.0.0
repository: https://github.com/je0ngmin/hangul_utils

environment:
  sdk: ^3.9.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
